# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build for Linux
      run: go build

    - name: Upload linux release
      uses: actions/upload-artifact@v4
      with:
        name: Linux release
        path: hexadecimal-binary

    - name: Build for Windows
      run: GOOS=windows GOARCH=amd64 go build

    - name: Upload Windows release
      uses: actions/upload-artifact@v4
      with:
        name: Windows release
        path: hexadecimal-binary.exe
